name: "zabbix-ts-servers"

services:

  zabbix-agent-2:
    image: zabbix/zabbix-agent2:alpine-7.0-latest
    networks:
      - zabbix
    privileged: true
    ports:
      - "10050:10050"

  zabbix-frontend:
    image: zabbix/zabbix-web-nginx-mysql:alpine-7.0-latest
    networks:
      - zabbix
    depends_on:
      - db
    env_file:
      - envs-zabbix-docker
    ports:
      - "8000:8080"

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-7.0-latest
    networks:
      - zabbix
    depends_on:
      - db
    env_file:
      - envs-zabbix-docker
    ports:
      - "10051:10051"
    restart: unless-stopped

  db:
    image: mysql:9
    env_file:
      - envs-zabbix-docker
    networks:
      - zabbix
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"

networks:
  zabbix:
volumes:
  mysql: