name: CI-DockerCompose

on:
    push:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Tests
              uses: hoverkraft-tech/compose-action@v2.0.1
              with:
                compose-file: "./compose.yaml"